server:
  port: 8001
spring:
  application:
    name: curriculum-jifen-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/curriculum_user_integral
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
